// Generated by CoffeeScript 1.9.1
(function() {
  Array.prototype.any(function(predicate, args) {
    var i, result;
    result = false;
    if (!predicate) {
      result = this.length > 0;
    } else {
      i = 0;
      while (i < this.length) {
        if (predicate(this[i], args)) {
          result = true;
          break;
        }
        i++;
      }
    }
    return result;
  });

  Array.prototype.first(function(predicate, args) {
    var i, result;
    result = null;
    if (!predicate && this.any) {
      result = this[0];
    } else {
      i = 0;
      while (i < this.length) {
        if (predicate(this[i], args)) {
          result = this[i];
          break;
        }
        i++;
      }
    }
    return result;
  });

  Array.prototype.forEach(function(action, args) {
    var arg, j, len;
    for (j = 0, len = args.length; j < len; j++) {
      arg = args[j];
      action(arg);
    }
  });

  Array.prototype.select(function(func, args) {
    var arg, j, len, results;
    results = [];
    for (j = 0, len = args.length; j < len; j++) {
      arg = args[j];
      results.push(func(arg));
    }
    return results;
  });

  Array.prototype.where(function(predicate) {
    var i, result;
    result = [];
    i = 0;
    while (i < this.length) {
      if (predicate(this[i])) {
        result.push(this[i]);
      }
      i++;
    }
    return result;
  });

  Date.prototype.format(function(format) {
    var result;
    result = format;
    result = result.replace('dd', this.getDate().toString().padLeft(2, '0'));
    result = result.replace('d', this.getDate());
    result = result.replace('mm', (this.getMonth() + 1).toString().padLeft(2, '0'));
    result = result.replace('m', this.getMonth() + 1);
    result = result.replace('yyyy', this.getFullYear());
    result = result.replace('HH', this.getHours().toString().padLeft(2, '0'));
    result = result.replace('H', this.getHours());
    result = result.replace('MM', this.getMinutes().toString().padLeft(2, '0'));
    result = result.replace('M', this.getMinutes());
    result = result.replace('SS', this.getSeconds().toString().padLeft(2, '0'));
    result = result.replace('S', this.getSeconds());
    return result;
  });

  Date.today(function() {
    var now, today;
    now = new Date();
    today = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0, 0, 0, 0);
    return today;
  });

  Date.prototype.addDays(function(days) {
    return new Date(this.getFullYear(), this.getMonth(), this.getDate() + days, this.getHours(), this.getMinutes(), this.getSeconds(), this.getMilliseconds());
  });

  Date.prototype.addMonths(function(months) {
    return new Date(this.getFullYear(), this.getMonth() + months, this.getDate(), this.getHours(), this.getMinutes(), this.getSeconds(), this.getMilliseconds());
  });

}).call(this);
